import React from 'react';
import './healthtips.css'
const HealthTips = () => {
    return (
        <div className='healthtips'>
            <h1>Health Tips</h1>
            <p>Health care embraces all the goods and services designed to promote health, including preventive, curative, and palliative interventions whether directed to individuals or populations [1]. It is, therefore, a necessity and a basic human need. Based on that recognition, the Alma-Ata declaration of the 1978 Primary Health Care (PHC) conference, endorsed by practically all governments, called for social and economic guarantees that would ensure that the basic health needs for all citizens of the world will be achieved by or before the year 2000 [2]. When the goal post of the Alma-Ata declaration was almost approaching, representatives from 189 countries met at the Millennium Summit in New York to adopt the Millennium Development Goals (MDGs). The MDGs just like the PHC declaration also place health at the heart of development and represent commitment by governments throughout the world to reduce poverty and hunger, lack of education, and gender inequality and to tackle ill-health conditions [3]. Unfortunately, for most developing countries, the prospects of achieving even a minimal level of adequacy in health services and health remains a mirage. While health care needs are increasing, governments’ expenditure on health in developing countries is declining [4].

Health care providers in Nigeria in the precolonial period were predominantly made up of traditional healers and diviners. In the colonial era there was a paradigm shift from the traditional health practice to orthodox and traditional medical services running concurrently. In these cases, orthodox medical services that were initially meant for the British Army were later extended to members of the colonial government and local populations living close to them. Various religious bodies later further established hospitals to supplement the efforts of the government and that continued until the postindependence era [5]. Now it is a concurrent responsibility of the three tiers of government (local, state, and national) in the country to provide orthodox medical care to the citizenry. However, because Nigeria operates a mixed economy, private providers of health care and tradomedical health practitioners still have a visible role to play in health care delivery as well [6]. Despite the existence of these public and private health services, Nigeria as a country has never been able to meet up with the international standards that have been set for the advancement of health over the years. Nigeria’s poor health care system has been described as alarming by many authorities, and that calls for urgent attention from the government at all levels as well as medical practitioners [6, 7]. In 2011, Nigeria’s health care system was ranked 51st out of 53 countries in Africa, as against the case in the 60s and 70s, when Nigeria was ranked 4th in the Commonwealth [8].

Various contributory factors have been identified at the individual level, communities, and societal levels. For instance, due to poor leadership and poor political commitment, the federal government still has a low health expenditure of about 1.5% to over 150 million Nigerians [9]. These coupled with the skewed distribution of public health facilities in the country left the rural areas with high disease morbidity and mortality. About 70% of the health facilities are situated in the urban areas, while 30% are in the rural areas. However, 70% of health-related conditions are found in the rural areas where poverty also abounds [6, 9]. At the individual level, poverty and ignorance remain as the most important determinants of ill-health as they contribute significantly to increasing exposure to disease-causing agents and also prevent access to health care services. Over 20 percent of foreign patients seeking medical attention in most developed countries are from Nigeria, but the majority of these patients are, of course, the well-to-do individuals in the society. The poor ones who are in the rural areas, who have issues of poverty to contend with, cannot afford medical bills outside the shores of Nigeria. Within the country, most hospital expenditures incurred by these same poor patients are made out of pocket [6–8, 10]. Other determinant factors reported by some scholars include the age of the patient, their occupation, the nature of illness they experienced, and the functional status of the health facilities which the patients visit (i.e., in terms of the attitude and skill of staff) [7, 9, 10].

Just like any other part of the country, Benue State is not exempted. Benue State Ministry of Health (BSMoH) Report of 2009 shows that Benue State with a projected population of 4,497,988 in 2008 had 368 registered medical doctors giving doctor-patient ratio of 1 : 12,222, while the number of registered nurses/midwives is 2,172 representing nurse-patient ratio of 1 : 2,071 [11]. This study, therefore, focused on the utilization of health care services in rural areas in Benue State, based on four conceptual predictions. The first is that the patient’s utilization of health services largely depends on their socioeconomic status. The second factor is based on the assumption that the income of people greatly affects their choice of health care services [12]. Another dimension is the perception of illness and the availability of health facilities, which may determine the use of health facilities [13]. Finally, the fourth dimension is the establishment of the association between the socioeconomic status of the household heads and their belief system which may influence their health-seeking preference for themselves, other adults, and young members of their families [14].

2. Materials and Methods
2.1. Study Location
The study was community-based, conducted in Apa Local Government Area (LGA) of Benue State from January through February 2012. Apa is one of the twenty-three LGAs in Benue State, North Central Nigeria. The Local Government Area was created in August 1991 by the then Military Head of State of Nigeria, General Ibrahim Badamosi Babangida, covering what was the old Ochekwu District of Otukpo LGA. The LGA is made up of 84 villages (settlements) divided into 11 political districts/wards. The major big villages in the LGA include Ugboko (the headquarters), Oiji, Ojantele, Akpete, Iga-Okpaya, Ikobi, Odugbo, Ofoke, Oba Alifeti, Idada, Edikwu-Icho, Ugbobi, Ebugodo, and Opaha. The LGA has an estimated population of 996,000 (2006 population census). The Local Government Area shares boundary with Agatu, Otukpo, and Gwer-West Local Government Areas of Benue State to its north, south, and east, respectively, while to its west, it is bordered by Ankpa and Omala Local Government Areas of Kogi State. The Local Government Area is blessed with abundant forest resources and is one of the main sources of timber to big towns like Otukpo. The Local Government Area is also known for its agricultural products with cassava, maize, yam, melon, and guinea-corn being the main farm produce. The people of the Local Government Area predominantly speak a dialect of Idoma language. There is a Comprehensive Health Care Centre located at Ugbokpo which serves as a referral health centre for the people of the LGA. In addition, there is a Primary Health Care (PHC) facility in each of the district headquarters providing health care services to the people. Other health care providers include formal private providers, informal private providers, patent medicine vendors, traditional healers, and faith healers [15].

2.2. Study Population and Design
A cross-sectional, community-based, descriptive study design was employed for the study. The study population was the household heads in all the settlements of the 11 districts/wards. The household heads who had experienced any disease episode in the three months prior to the survey were included while those who were not around at the time of the study and those who had never experienced any disease episode 3 months prior to the survey were excluded from the study. Those who did not consent were also excluded.</p>
        </div>
    );
};

export default HealthTips;